enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
patches-source = "inotia00/revanced-patches"
rv-brand = "ReVanced eXtended"
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
build-mode = "module"
arch = "arm64-v8a"
excluded-patches = "'Custom branding icon for YouTube' 'Translations for YouTube' 'Custom branding name for YouTube' 'Theme' 'MaterialYou' 'Enable gradient loading screen' 'Force hide player buttons background'"
included-patches = "'Visual preferences icons'"
patcher-args = " -e 'GmsCore support' -OpackageNameYouTube='com.rvx.android.youtube'"
version = "auto"
exclusive-patches = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "yt-rvx"

[Music]
arch = "arm64-v8a"
build-mode = "module"
app-name = "YouTube-Music"
excluded-patches = "'Custom branding Icon for YouTube Music' 'Custom branding name for YouTube Music' 'Dark theme'"
included-patches = ""
patcher-args = " -e 'GmsCore support' -OpackageNameYouTubeMusic='com.rvx.android.youtube.music'"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
module-prop-name = "ytm-rvx"

